import {
  Sparkles, LayoutDashboard, BookOpen, Video, BarChart2, ShieldAlert,
  Settings, Search, Edit3, Bell, MessageSquare, User, Users, Shield,
  GraduationCap, Rocket,
} from 'lucide-react';
import type { TourStep } from './SpotlightTour';

/** Instructor onboarding — focuses on teaching workflow. */
export const instructorTour: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to APES LMS 👋',
    body: 'Let’s take a quick, guided spin around your instructor workspace. We’ll highlight one thing at a time — it takes under a minute.',
    icon: Sparkles,
    route: '/dashboard',
  },
  {
    id: 'dashboard-hero',
    title: 'Your Dashboard',
    body: 'This is home base. Jump straight into creating a course or adding a category right from the welcome banner.',
    icon: LayoutDashboard,
    target: '[data-tour="dashboard-hero"]',
    route: '/dashboard',
    placement: 'bottom',
  },
  {
    id: 'dashboard-stats',
    title: 'At-a-glance metrics',
    body: 'Active courses, students, and submissions update live so you always know where things stand.',
    icon: BarChart2,
    target: '[data-tour="dashboard-stats"]',
    route: '/dashboard',
    placement: 'bottom',
  },
  {
    id: 'nav-courses',
    title: 'My Courses',
    body: 'Build and manage every course here. Open a course to add sections, activities, quizzes, and resources.',
    icon: BookOpen,
    target: '[data-tour="nav-courses"]',
    tip: 'Enable Edit Mode first to add or rearrange content inside a course.',
    placement: 'bottom',
  },
  {
    id: 'edit-mode',
    title: 'Edit Mode',
    body: 'Flip this toggle to add, edit, and reorder course content. An amber banner reminds you while it’s on.',
    icon: Edit3,
    target: '[data-tour="edit-mode"]',
    placement: 'bottom',
  },
  {
    id: 'nav-sessions',
    title: 'Live Sessions',
    body: 'Schedule and launch live video classes for your students, complete with recording and attendance.',
    icon: Video,
    target: '[data-tour="nav-sessions"]',
    placement: 'bottom',
  },
  {
    id: 'nav-engagement',
    title: 'Engagement Analytics',
    body: 'See who’s active, who’s falling behind, and which activities drive participation — AI surfaces at-risk students automatically.',
    icon: BarChart2,
    target: '[data-tour="nav-engagement"]',
    placement: 'bottom',
  },
  {
    id: 'nav-proctoring',
    title: 'Proctoring',
    body: 'Monitor quiz and exam integrity with live proctoring sessions and flagged-event review.',
    icon: ShieldAlert,
    target: '[data-tour="nav-proctoring"]',
    placement: 'bottom',
  },
  {
    id: 'nav-administration',
    title: 'Programme Management',
    body: 'Manage the students and courses assigned to your programme from one place.',
    icon: GraduationCap,
    target: '[data-tour="nav-administration"]',
    placement: 'bottom',
  },
  {
    id: 'search',
    title: 'Global Search',
    body: 'Find any course, activity, or student in seconds from anywhere in the app.',
    icon: Search,
    target: '[data-tour="search"]',
    placement: 'bottom',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    body: 'Real-time alerts for submissions, messages, and system updates land here.',
    icon: Bell,
    target: '[data-tour="notifications"]',
    placement: 'bottom',
  },
  {
    id: 'messages',
    title: 'Messages',
    body: 'Chat directly with students and colleagues without leaving the platform.',
    icon: MessageSquare,
    target: '[data-tour="messages"]',
    placement: 'bottom',
  },
  {
    id: 'profile',
    title: 'Your Account',
    body: 'Update your profile, notification preferences, and sign out from the avatar menu.',
    icon: User,
    target: '[data-tour="profile"]',
    placement: 'bottom',
  },
  {
    id: 'done',
    title: 'You’re all set! 🚀',
    body: 'That’s the tour. You can replay it anytime from the “New here?” prompt or your profile menu. Now go build something great.',
    icon: Rocket,
  },
];

/** Admin onboarding — focuses on platform governance. */
export const adminTour: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome, Administrator 👋',
    body: 'Here’s a quick guided tour of the controls you’ll use to run the platform. We’ll spotlight one area at a time.',
    icon: Sparkles,
    route: '/dashboard',
  },
  {
    id: 'dashboard-stats',
    title: 'Platform Overview',
    body: 'Your dashboard summarizes activity across every college, programme, and course at a glance.',
    icon: LayoutDashboard,
    target: '[data-tour="dashboard-stats"]',
    route: '/dashboard',
    placement: 'bottom',
  },
  {
    id: 'nav-administration',
    title: 'Administration Center',
    body: 'This is your command center for users, courses, colleges, programmes, and system settings.',
    icon: Settings,
    target: '[data-tour="nav-administration"]',
    placement: 'bottom',
  },
  {
    id: 'admin-stats',
    title: 'Governance Metrics',
    body: 'Total users, active courses, colleges, and degree programmes — the health of your whole institution.',
    icon: BarChart2,
    target: '[data-tour="admin-stats"]',
    route: '/administration',
    placement: 'bottom',
  },
  {
    id: 'admin-users',
    title: 'User Management',
    body: 'Create, edit, and assign roles to students, instructors, and admins. Bulk actions live here too.',
    icon: Users,
    target: '[data-tour="admin-tab-users"]',
    route: '/administration',
    tip: 'Only admins can create instructor and admin accounts.',
    placement: 'bottom',
  },
  {
    id: 'admin-system',
    title: 'System Settings',
    body: 'Configure colleges, integrations, and platform-wide settings from the System tab.',
    icon: Shield,
    target: '[data-tour="admin-tab-system"]',
    route: '/administration',
    placement: 'bottom',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    body: 'Stay on top of reports, approvals, and system events in real time.',
    icon: Bell,
    target: '[data-tour="notifications"]',
    placement: 'bottom',
  },
  {
    id: 'profile',
    title: 'Your Account',
    body: 'Manage your profile, admin preferences, and session from the avatar menu.',
    icon: User,
    target: '[data-tour="profile"]',
    placement: 'bottom',
  },
  {
    id: 'done',
    title: 'Ready to go 🚀',
    body: 'That’s the essentials. Replay this tour anytime from the “New here?” prompt or your profile menu.',
    icon: Rocket,
  },
];

export function getTourForRole(role?: string): TourStep[] {
  return role === 'admin' ? adminTour : instructorTour;
}
